<a href="https://colab.research.google.com/github/nesredingebeyehu15-dot/My-AI-Engineering-Journey/blob/main/Day_09_Integration_Arena.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
# DAY 9 ARENA: THE REGISTRAR'S NIGHTMARE (SOLVED)
import pandas as pd
import numpy as np

# 1. GENERATE DATA
students = pd.DataFrame({
    'Student_ID': ['UG01', 'UG02', 'UG03', 'UG04', 'UG05', 'UG01'],
    'Name': ['  abebe', 'SARA ', 'chala', '  Marta', 'Zewdu', '  abebe'],
    'Department': ['CS', 'SE', 'CS', 'SE', 'CS', 'CS']
})

grades = pd.DataFrame({
    'Student_ID': ['UG01', 'UG02', 'UG03', 'UG05', 'UG99'],
    'Math': ['80', '90', 'NaN', '60', '50'],
    'Physics': [70, 85, 60, 55, 40]
})

print("--- 1. RAW DATA ---")
display(students)
display(grades)

# 2. CLEANING STUDENTS (The Fix)
# Step A: Clean Name Text
students['Name'] = students['Name'].str.strip().str.title()

# Step B: Drop Duplicates (The Correct Way)
# ሙሉውን መስመር ነው የምናጠፋው
students = students.drop_duplicates()

print("\n--- 2. CLEANED STUDENTS ---")
display(students)

# 3. CLEANING GRADES
# Step A: Handle NaN in Math
# pd.to_numeric with errors='coerce' is safer than astype(float) for dirty text
grades['Math'] = pd.to_numeric(grades['Math'], errors='coerce')
grades['Math'] = grades['Math'].fillna(0)

print("\n--- 3. CLEANED GRADES ---")
display(grades)

# 4. MERGING
merged_file = pd.merge(students, grades, on='Student_ID', how='inner')

# 5. FEATURE ENGINEERING
merged_file['Total'] = merged_file['Math'] + merged_file['Physics']

# Status Logic (Excellent use of np.where!)
merged_file['Status'] = np.where(merged_file['Total'] >= 100, "Pass", "Fail")

print("\n--- 4. FINAL REPORT ---")
display(merged_file)

# 6. ANALYSIS
avg_by_dept = merged_file.groupby('Department')['Total'].mean()

print("\n--- 5. DEPT PERFORMANCE ---")
display(avg_by_dept)

--- 1. RAW DATA ---

  Student_ID     Name Department
0       UG01    abebe         CS
1       UG02    SARA          SE
2       UG03    chala         CS
3       UG04    Marta         SE
4       UG05    Zewdu         CS
5       UG01    abebe         CS

  Student_ID Math  Physics
0       UG01   80       70
1       UG02   90       85
2       UG03  NaN       60
3       UG05   60       55
4       UG99   50       40

--- 2. CLEANED STUDENTS ---

  Student_ID   Name Department
0       UG01  Abebe         CS
1       UG02   Sara         SE
2       UG03  Chala         CS
3       UG04  Marta         SE
4       UG05  Zewdu         CS

--- 3. CLEANED GRADES ---

  Student_ID  Math  Physics
0       UG01  80.0       70
1       UG02  90.0       85
2       UG03   0.0       60
3       UG05  60.0       55
4       UG99  50.0       40

--- 4. FINAL REPORT ---

  Student_ID   Name Department  Math  Physics  Total Status
0       UG01  Abebe         CS  80.0       70  150.0   Pass
1       UG02   Sara         SE  90.0       85  175.0   Pass
2       UG03  Chala         CS   0.0       60   60.0   Fail
3       UG05  Zewdu         CS  60.0       55  115.0   Pass

--- 5. DEPT PERFORMANCE ---

Department
CS    108.333333
SE    175.000000
Name: Total, dtype: float64