<a href="https://colab.research.google.com/github/nesredingebeyehu15-dot/My-AI-Engineering-Journey/blob/main/Day_12_Arena_Lambda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
# DAY 12 ARENA: HR EMAIL GENERATOR (EXPERT EDITION)
# Author: Nesredin Gebeyehu
# Objective: Generate Corporate Emails and Passwords using Lambda

import pandas as pd

# ==========================================
# 1. DATA INGESTION
# ==========================================
employees = pd.DataFrame({
    'ID': [101, 102, 103, 104],
    'First_Name': ['  abebe', 'SARA', 'Tola', 'marta'],
    'Last_Name': ['Kebede', '  ALI', 'Bekele', 'Yilma'],
    'Birth_Year': [1990, 1995, 1988, 2000]
})

print("--- 1. RAW DATA ---")
display(employees)

# ==========================================
# 2. CLEANING (GLOBAL FIX)
# ==========================================
# Clean BOTH names first. This makes the dataframe clean for everyone.
employees['First_Name'] = employees['First_Name'].str.strip().str.lower()
employees['Last_Name'] = employees['Last_Name'].str.strip().str.lower()

# ==========================================
# 3. FEATURE ENGINEERING (LAMBDA)
# ==========================================

# A. Generate Email (firstname.lastname@company.com)
# Fixed: Changed ',' to '.'
employees['Email'] = employees.apply(
    lambda row: f"{row['First_Name']}.{row['Last_Name']}@company.com",
    axis=1
)

# B. Generate Password (Capitalized Name + Year)
# Using f-string inside lambda is cleaner!
employees['Password'] = employees.apply(
    lambda row: f"{row['First_Name'].capitalize()}{row['Birth_Year']}",
    axis=1
)

print("\n--- 2. FINAL HR DATA ---")
display(employees)

--- 1. RAW DATA ---

    ID First_Name Last_Name  Birth_Year
0  101      abebe    Kebede        1990
1  102       SARA       ALI        1995
2  103       Tola    Bekele        1988
3  104      marta     Yilma        2000

--- 2. FINAL HR DATA ---

    ID First_Name Last_Name  Birth_Year                     Email   Password
0  101      abebe    kebede        1990  abebe.kebede@company.com  Abebe1990
1  102       sara       ali        1995      sara.ali@company.com   Sara1995
2  103       tola    bekele        1988   tola.bekele@company.com   Tola1988
3  104      marta     yilma        2000   marta.yilma@company.com  Marta2000