<a href="https://colab.research.google.com/github/nesredingebeyehu15-dot/My-AI-Engineering-Journey/blob/main/Day_12_Lambda_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
# DAY 12: LAMBDA FUNCTIONS (PROFESSIONAL EDITION)
# Author: Nesredin Gebeyehu
# Objective: Apply Lambda functions for calculations and text formatting

import pandas as pd
import numpy as np

# ==========================================
# 1. DATA INGESTION
# ==========================================
data = {
    'Product': ['Laptop', 'Mouse', 'Keyboard', 'Monitor'],
    'Price': [1000, 20, 50, 200],
    'Stock': [5, 0, 10, 2]
}

df = pd.DataFrame(data)

print("--- 1. RAW DATA ---")
display(df)

# ==========================================
# 2. LAMBDA TRANSFORMATIONS
# ==========================================

# A. Calculate Price with VAT (15%)
# Using lambda for simple arithmetic
df['Price_with_VAT'] = df['Price'].apply(lambda x: x * 1.15)

# B. Standardize Product Names (Uppercase)
# Using lambda for string manipulation
df['Product'] = df['Product'].apply(lambda x: x.upper())

# C. Inventory Status Logic
# Using lambda for conditional logic (If/Else)
df['Status'] = df['Stock'].apply(lambda x: 'Available' if x > 0 else 'Out of Stock')

print("\n--- 2. PROCESSED DATA ---")
display(df)

--- 1. RAW DATA ---

    Product  Price  Stock
0    Laptop   1000      5
1     Mouse     20      0
2  Keyboard     50     10
3   Monitor    200      2

--- 2. PROCESSED DATA ---

    Product  Price  Stock  Price_with_VAT        Status
0    LAPTOP   1000      5          1150.0     Available
1     MOUSE     20      0            23.0  Out of Stock
2  KEYBOARD     50     10            57.5     Available
3   MONITOR    200      2           230.0     Available