<a href="https://colab.research.google.com/github/nesredingebeyehu15-dot/My-AI-Engineering-Journey/blob/main/Day_11_Pivot_and_Apply.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
# DAY 11: PIVOT TABLES & CUSTOM LOGIC (PROFESSIONAL EDITION)
# Author: Nesredin Gebeyehu
# Objective: Analyze Student Grades using Pivot Tables and Apply Functions

import pandas as pd
import numpy as np

# ==========================================
# 1. DATA INGESTION
# ==========================================
student_grades = {
    'Student': ['Abebe', 'Sara', 'Tola', 'Marta'],
    'Subject': ['Math', 'Math', 'English', 'English'],
    'Score': [85, 45, 90, 30]
}

df = pd.DataFrame(student_grades)

print("--- 1. RAW DATA ---")
display(df)

# ==========================================
# 2. PIVOT TABLE (THE GRID VIEW)
# ==========================================
# Professional Tip: Always define 'aggfunc' (sum/mean) to avoid ambiguity.
# 'fill_value=0' ensures no NaN if a student missed a subject.
df_pivot = df.pivot_table(
    index='Student',
    columns='Subject',
    values='Score',
    aggfunc='sum',
    fill_value=0
)

print("\n--- 2. PIVOT TABLE REPORT ---")
display(df_pivot)

# ==========================================
# 3. CUSTOM LOGIC (APPLY FUNCTION)
# ==========================================

def get_grade_status(score: int) -> str:
    """
    Determines if a student Passed or Failed based on score.
    Threshold: 50
    """
    if score >= 50:
        return "Pass"
    else:
        return "Fail"

# Apply the function row by row
df['Status'] = df['Score'].apply(get_grade_status)

print("\n--- 3. FINAL REPORT WITH STATUS ---")
display(df)

# ==========================================
# SENIOR ENGINEER TIP (OPTIMIZATION)
# ==========================================
# For millions of rows, 'apply' can be slow.
# 'np.where' is 100x faster. Here is how pros do it:
df['Status_Pro'] = np.where(df['Score'] >= 50, 'Pass', 'Fail')
# display(df)

--- 1. RAW DATA ---

  Student  Subject  Score
0   Abebe     Math     85
1    Sara     Math     45
2    Tola  English     90
3   Marta  English     30

--- 2. PIVOT TABLE REPORT ---

Subject  English  Math
Student
Abebe          0    85
Marta         30     0
Sara           0    45
Tola          90     0

--- 3. FINAL REPORT WITH STATUS ---

  Student  Subject  Score Status
0   Abebe     Math     85   Pass
1    Sara     Math     45   Fail
2    Tola  English     90   Pass
3   Marta  English     30   Fail