<a href="https://colab.research.google.com/github/nesredingebeyehu15-dot/My-AI-Engineering-Journey/blob/main/Day_04_Filtering/filtering_logic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# DAY 04: FILTERING LOGIC (RE-COMMIT)
import pandas as pd

# 1. DATA
data = {
    'Name': ['Abebe', 'Kebede', 'Sara', 'Marta', 'Tola', 'Zewdu'],
    'Department': ['IT', 'Sales', 'IT', 'HR', 'Sales', 'IT'],
    'Salary': [5000, 7000, 5200, 4500, 8000, 12000],
    'Performance': [90, 60, 95, 85, 50, 98]
}
df = pd.DataFrame(data)

# 2. CHALLENGES SOLVED
# Challenge A: Sales Dept
print("--- Sales Dept ---")
display(df[df['Department'] == 'Sales'])

# Challenge B: Underperformers (< 70)
print("\n--- Underperformers ---")
display(df[df['Performance'] < 70])

# Challenge C: Low Salary OR Low Performance
print("\n--- Critical Review Needed ---")
display(df[(df['Salary'] < 5000) | (df['Performance'] < 60)])

--- Sales Dept ---

     Name Department  Salary  Performance
1  Kebede      Sales    7000           60
4    Tola      Sales    8000           50

--- Underperformers ---

     Name Department  Salary  Performance
1  Kebede      Sales    7000           60
4    Tola      Sales    8000           50

--- Critical Review Needed ---

    Name Department  Salary  Performance
3  Marta         HR    4500           85
4   Tola      Sales    8000           50